require(data.table)
require(stargazer)
ceosal<-data.table(data)
nrow(ceosal)
colnames(ceosal)
head(ceosal)
summary(ceosal)
stargazer(ceosal, type = 'text')
lm1<- lm(lsalary ~ lsales + lmktval, data = ceosal)
stargazer(lm1, type = 'text')
lm2<- lm(lsalary ~ lsales + lmktval+ profits, data = ceosal)
stargazer(lm2, type = 'text')
stargazer(lm1, type = 'text')
lm3<- lm(lsalary ~ lsales + lmktval+ profits + ceoten + comten, data = ceosal)
stargazer(lm3, type = 'text')
new.ceosal<-data.table(salary = 1161,600,397)
my.pred <-predict(ceosal, newdata = new.ceosal)
residuals(ceosal)
residuals( lm(lsalary ~ lsales + lmktval+ profits + ceoten + comten, data = ceosal)
          stargazer(lm3, type = 'text')
resid(lm1)
cor(lmktval, profits , data =ceosal)
cor(profits, lmktval)
head(ceosal)
ceosal[, c(profits, lmktval)]
cor(profits +lmktval, data= ceosal)